oc-gw: improve "homelab mode" detection
 * instead of looking for an opencloud container, which is actually also
   running when debugging in the IDE while using the "homelab mode"
   since the opencloud container is used to provide IDM and IDP
   services, do check whether something is listening on the
   localhost:9200

diff --git a/oc-gw b/oc-gw
--- a/oc-gw
+++ b/oc-gw
@@ -8,21 +8,41 @@ set -euo pipefail
 : "${realm:=openCloud}"
 : "${client_id:=groupware}"
 : "${opencloud_container:=opencloud_full-opencloud-1}"
+: "${opencloud_local_port:=9200}"
 
 # find out whether we have basic auth enabled
 declare -a auth
 container=
-if [[ -n $(docker ps -q -f name="${opencloud_container}") ]]; then
+
+
+if exec 6<>/dev/tcp/127.0.0.1/"${opencloud_local_port}"; then
+  # running locally
+  baseurl="https://localhost:9200"
+  # assuming it is with basic auth support
+  auth=("-A" "basic" "-a" "${username}:${password}")
+elif [[ -n $(docker ps -q -f name="${opencloud_container}") ]]; then
   # container is running
   container=1
   basic_auth=$(docker inspect "${opencloud_container}"|jq -r '.[].Config.Env[]|select(match("^PROXY_ENABLE_BASIC_AUTH="))|.[index("=")+1:]')
   if [[ "${basic_auth}" == "true" ]]; then
     auth=("-A" "basic" "-a" "${username}:${password}")
+  else
+    # empty auth array, will trigger fetching an access token
+    auth=()
   fi
 else
-  # container is not running, assume it's running in the IDE
-  baseurl="https://localhost:9200"
+  # not listening locally, nor running as a container
+  if [[ -z "${baseurl}" ]]; then
+    echo "ERROR: not running locally on \${opencloud_local_port} (${opencloud_local_port}) nor running as a container \${opencloud_container} ('${opencloud_container}') and \${baseurl} is not set either" >&2
+    exit 9
+  else
+    # assuming we need to fetch a token
+    auth=()
+  fi
 fi
+
+exec 6>&- # close output connection
+exec 6<&- # close input connection
 
 url="${baseurl}"
 if [[ -z "${url}" ]]; then
